import React from 'react';
import { Inter } from 'next/font/google';
import Footer from './components/Footer';
import Subscribe from './components/Subscribe';
import './globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Subscribe />
        <Footer />
      </body>
    </html>
  );
}
