import React from 'react';
import { Inter } from 'next/font/google';
import Subscribe from './components/Subscribe';
import Footer from './components/Footer';
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Timbu | Online store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Subscribe />
        <Footer />
      </body>
    </html>
  );
}
